# Generated by Django 5.0.4 on 2024-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='bussiness',
            field=models.BooleanField(default=False),
        ),
    ]
