# Generated by Django 5.0.4 on 2024-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_signup_bussiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='bussiness',
        ),
        migrations.AddField(
            model_name='signup',
            name='business',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
