# Generated by Django 5.0.4 on 2024-06-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_remove_signup_bussiness_signup_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='business',
            new_name='bussiness',
        ),
    ]
