# Generated by Django 5.0.4 on 2024-06-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_rename_business_signup_bussiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
