# Generated by Django 5.0.4 on 2024-07-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
