# Generated by Django 5.0.4 on 2024-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('open_until', models.TimeField()),
                ('experience', models.IntegerField()),
                ('timing', models.CharField(max_length=100)),
                ('service', models.TextField()),
                ('overview', models.TextField()),
                ('image', models.ImageField(upload_to='business_images/')),
            ],
        ),
    ]
