# Generated by Django 5.0.4 on 2024-06-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0002_remove_business_country'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category'),
        ),
    ]
