# Generated by Django 5.0.4 on 2024-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0005_alter_business_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
