# Generated by Django 5.0.4 on 2024-06-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0007_message'),
        ('Login', '0004_rename_business_signup_bussiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddBussiness.business'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.signup'),
        ),
    ]
