# Generated by Django 5.0.4 on 2024-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0008_alter_message_business_id_alter_message_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='business_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
