# Generated by Django 5.0.4 on 2024-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0014_alter_business_open_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='youtube',
            field=models.CharField(default='', max_length=500),
        ),
    ]
