# Generated by Django 5.0.4 on 2024-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0015_business_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='youtube',
            field=models.CharField(default='', max_length=200),
        ),
    ]
