# Generated by Django 5.0.4 on 2024-06-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0017_alter_business_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='youtube',
        ),
    ]
