# Generated by Django 5.0.4 on 2024-06-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0018_remove_business_youtube'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.CharField(default='', max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('open_until', models.TimeField()),
                ('experience', models.IntegerField()),
                ('timing', models.CharField(max_length=100)),
                ('service', models.TextField()),
                ('overview', models.TextField()),
                ('youtube', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='business_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
