# Generated by Django 5.0.4 on 2024-06-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0019_newbussiness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewBussiness',
        ),
    ]
