# Generated by Django 5.0.4 on 2024-06-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0021_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
