# Generated by Django 5.0.4 on 2024-06-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0025_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='business_gallery/')),
            ],
        ),
    ]
