# Generated by Django 5.0.4 on 2024-06-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0026_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
