# Generated by Django 5.0.4 on 2024-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0027_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='open_until',
            field=models.CharField(max_length=100),
        ),
    ]
