# Generated by Django 5.0.4 on 2024-06-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0028_alter_business_experience_alter_business_open_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='adv',
            field=models.CharField(default='', max_length=200),
        ),
    ]
