# Generated by Django 5.0.4 on 2024-06-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0029_business_adv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='adv',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='youtube',
        ),
    ]
