# Generated by Django 5.0.4 on 2024-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0030_remove_business_adv_remove_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='adv',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='youtube',
            field=models.CharField(default='', max_length=200),
        ),
    ]
