# Generated by Django 5.0.4 on 2024-06-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0031_business_adv_business_email_business_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='adv',
        ),
    ]
