# Generated by Django 5.0.4 on 2024-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0032_remove_business_adv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField()),
                ('user', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('search', models.CharField(max_length=200)),
            ],
        ),
    ]
