# Generated by Django 5.0.4 on 2024-06-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0033_lead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
