# Generated by Django 5.0.4 on 2024-06-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0036_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
