# Generated by Django 5.0.4 on 2024-06-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddBussiness', '0038_advertisement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Adv',
        ),
    ]
